import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.plugin.mpp.apple.XCFramework

plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.android.library)
    `maven-publish`
}

kotlin {
    jvmToolchain(17)

    androidTarget {
        publishLibraryVariants("release")
        compilations.all {
            compileTaskProvider.configure {
                compilerOptions { jvmTarget.set(JvmTarget.JVM_11) }
            }
        }
    }
    jvm {
        compilations.all {
            compileTaskProvider.configure {
                compilerOptions { jvmTarget.set(JvmTarget.JVM_11) }
            }
        }
    }

    val xcf = XCFramework("PilotPartnerSdk")
    listOf(iosX64(), iosArm64(), iosSimulatorArm64()).forEach { target ->
        target.binaries.framework {
            baseName = "PilotPartnerSdk"
            xcf.add(this)
        }
    }

    applyDefaultHierarchyTemplate()

    sourceSets {
        commonMain.dependencies {
            api(libs.kotlinx.coroutines.core)
            api(libs.kotlinx.serialization.json)
            api(libs.kotlinx.datetime)
            api(libs.ktor.client.core)
            api(libs.ktor.client.content.negotiation)
            api(libs.ktor.serialization.kotlinx.json)
            api(libs.ktor.client.logging)
            implementation(libs.kotlincrypto.macs.hmac.sha2)
        }
        commonTest.dependencies {
            implementation(libs.kotlin.test)
            implementation(libs.ktor.client.mock)
            implementation(libs.assertk)
            implementation(libs.kotlinx.coroutines.test)
        }
        // JVM + Android share the OkHttp Ktor engine.
        val jvmAndAndroidMain by creating { dependsOn(commonMain.get()) }
        androidMain {
            dependsOn(jvmAndAndroidMain)
            dependencies { api(libs.ktor.client.okhttp) }
        }
        jvmMain {
            dependsOn(jvmAndAndroidMain)
            dependencies { api(libs.ktor.client.okhttp) }
        }
        iosMain.dependencies { api(libs.ktor.client.darwin) }
    }
}

android {
    namespace = "life.pilot.partner.sdk"
    compileSdk = 35
    defaultConfig {
        minSdk = 24
        consumerProguardFiles("src/androidMain/resources/META-INF/proguard/pilot-partner-sdk.pro")
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }
    publishing { singleVariant("release") { withSourcesJar() } }
}

// Convenience wrapper task — the underlying task generated by the
// XCFramework DSL is `assemblePilotPartnerSdkReleaseXCFramework`. This
// shorter alias matches what the integration guide tells partners to run.
tasks.register("assembleXCFramework") {
    group = "build"
    description = "Assembles PilotPartnerSdk.xcframework (Release) for iOS SwiftPM distribution."
    dependsOn("assemblePilotPartnerSdkReleaseXCFramework")
}
